[package]
name = "assignment_1"
version = "0.1.0"
authors = ["Keith L <aradwhitelad@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
